### PR TITLE
added several bar charts and ski resort data

### PR DESCRIPTION
**Pull request by Ewiseman**

### CODE REVIEW

**Comment by eliotsykes** [comment]
@Ewiseman - very minor - there's a few Mac .DS_Store files added to the project repo. These can be safely removed from the git repo permanently.

Once they've been removed, I recommend adding a `.DS_Store` entry to the project's `.gitignore` file so they won't be added again.

**Comment by Ewiseman** [comment]
Hey Eliot, 

Thanks for you comment.  I did notice these were being added.  Where did they come from?  Also, how do I remove them from the git repo?  I dont see them in my profile folder.  This path does not exist?  app/assets/.DS_Store <https://github.com/Ewiseman/profile/pull/19/files#diff-79e13302a35ff32bbcfb6ee8a7ab59ec>

Eric

**Comment by eliotsykes** [comment]
@Ewiseman macOS adds them, .DS_Store files are:

> In the Apple macOS operating system, .DS_Store is a file that stores custom attributes of its containing folder, such as the position of icons or the choice of a background image.

Source: https://en.wikipedia.org/wiki/.DS_Store

Here's how to remove one of the files - do it for each one:
```
# Git remove the file so git no longer tracks it:
git rm -f app/assets/.DS_Store

git commit -m "Removed .DS_Store" app/assets/.DS_Store
```

>  I dont see them in my profile folder.

Any filename that begins with a period `.` like `.DS_Store` or `.bashrc` is known as a "hidden file". 

Hidden files are not visible by default, there are a couple of ways to see them:

```
# At the command line, pass the -a option to ls to show files that begin with a period:
ls -a
# or
ls -al
```

If you want to show hidden files in Finder by default (this is what I do), then this article explains how to set that up: http://www.macworld.co.uk/how-to/mac-software/how-show-hidden-files-in-mac-os-x-finder-funter-macos-sierra-3520878/

**Comment by eliotsykes** [comment]
PS. I would avoid the freeware program suggested by that article, just set the suggested config in the terminal.

**Pull request merged**
